Traceback (most recent call last):
  File "/Users/bylin/.pyenv/versions/3.9.10/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bylin/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/bylin/.pyenv/versions/3.9.10/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/bylin/.pyenv/versions/3.9.10/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bylin/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/bylin/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bylin/.pyenv/versions/3.9.10/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import random
import math
from string import ascii_letters
import ipywidgets as widgets

@widgets.interact(noise=(0,100,1), text='How was your day?')
def g(noise, text):
    n_to_swap = math.floor((len(text)*noise)/100)
    sam = random.sample(range(len(text)), n_to_swap)
    text = list(text)
    for ind in sam:
        text[ind] = random.choice(ascii_letters)
    return ''.join(text)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmath[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstring[39;00m [38;5;28;01mimport[39;00m ascii_letters
[0;32m----> 4[0m [38;5;28;01mimport[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mas[39;00m [38;5;21;01mwidgets[39;00m
[1;32m      6[0m [38;5;129m@widgets[39m[38;5;241m.[39minteract(noise[38;5;241m=[39m([38;5;241m0[39m,[38;5;241m100[39m,[38;5;241m1[39m), text[38;5;241m=[39m[38;5;124m'[39m[38;5;124mHow was your day?[39m[38;5;124m'[39m)
[1;32m      7[0m [38;5;28;01mdef[39;00m [38;5;21mg[39m(noise, text):
[1;32m      8[0m     n_to_swap [38;5;241m=[39m math[38;5;241m.[39mfloor(([38;5;28mlen[39m(text)[38;5;241m*[39mnoise)[38;5;241m/[39m[38;5;241m100[39m)

[0;31mModuleNotFoundError[0m: No module named 'ipywidgets'

